### ISSUE TITLE
Cannot login to hub - response is undefined

### ISSUE THREAD

**Issue by dermotos** [swissmanu/harmonyhubjs-client#20]
node app
/Users/d/Dropbox/Dev/HomeAutomation/HarmonyTest/node_modules/harmonyhubjs-client/lib/login/hub.js:63
			if(response.identity && response.identity !== undefined) {
			           ^

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/Users/d/Dropbox/Dev/HomeAutomation/HarmonyTest/node_modules/harmonyhubjs-client/lib/login/hub.js:63:15)
    at emitOne (events.js:78:13)
    at Client.emit (events.js:170:7)
    at Client.onStanza (/Users/d/Dropbox/Dev/HomeAutomation/HarmonyTest/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/index.js:231:14)
    at emitOne (events.js:78:13)
    at Connection.emit (events.js:170:7)
    at Connection.onStanza (/Users/d/Dropbox/Dev/HomeAutomation/HarmonyTest/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/lib/Connection.js:370:14)
    at StreamParser.<anonymous> (/Users/d/Dropbox/Dev/HomeAutomation/HarmonyTest/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/lib/Connection.js:226:14)
    at emitOne (events.js:78:13)
    at StreamParser.emit (events.js:170:7)

**Comment by swissmanu** [comment]
please refer to #15 and ensure you are using the latest version.
