### ISSUE TITLE
XMPP authentication failure not handled properly?

### ISSUE THREAD

**Issue by netactivenl** [swissmanu/harmonyhubjs-client#33]
I have about 400 clients running and many report the following error:

Error: Uncaught, unspecified "error" event. (XMPP authentication failure)
    at Client.emit (events.js:144:17)
    at Client._handleAuthState (/node_modules/node-xmpp-client/lib/Client.js:298:10)
    at Client._handleStanza (/node_modules/node-xmpp-client/lib/Client.js:234:12)
    at Client.onStanza (/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.onStanza (/node_modules/node-xmpp-core/lib/Connection.js:369:10)
    at StreamParser.<anonymous> (/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:77:13)
    at StreamParser.emit (events.js:169:7)

Seems like the harmonyhubjs-client (or one of its underlying libraries) doesn't handle this error properly, making my app crash randomly. Is there anything we (I) can do about this issue?

**Comment by beeguy1234** [comment]
+1  I have the exact same.
