### ISSUE TITLE
MAX_CLIENTS=6 ERROR, help?

### ISSUE THREAD

**Issue by sudochownrwhoami** [swissmanu/harmonyhubjs-client#34]
`
Error: MAX_CLIENTS=6
    at Connection.onStanza (/Volumes/SSD480/Dropbox/harmonyplayground/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/Volumes/SSD480/Dropbox/harmonyplayground/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/Volumes/SSD480/Dropbox/harmonyplayground/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/Volumes/SSD480/Dropbox/harmonyplayground/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/Volumes/SSD480/Dropbox/harmonyplayground/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/Volumes/SSD480/Dropbox/harmonyplayground/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
error: Forever detected script exited with code: 1
error: Script restart attempt #25`

What do you think is going on here? This used to happen awhile ago and now it happens every time, such that any communication with the hub causes this error.

**Comment by ToddGreenfield** [comment]
Is anyone working on this issue?

**Comment by tooh** [comment]
+1

**Comment by ToddGreenfield** [comment]
@tooh This error is mentioned in various threads and git repos- it does not appear it is being worked on and is a problem with the hub itself. A workaround for this error is to reset/unplug the hub, then restart your node service. I accomplished this by plugging the hub into a zwave outlet and having it switch off/on around 3am every day. Then I use a systemd.timer to restart my service (homebridge) which leverages a plugin dependent on this client. Been working with no issues for months now using two hubs.

**Comment by wayner9** [comment]
I am getting this error too, at least on the docker version of harmony-api.

Is this a limitation caused by Logitech (previously) only allowing six hubs linked to one account?  They have now changed that limit to 15.
